import dynamic from 'next/dynamic'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import react, { useState } from "react";
import Banner from '@/components/Home/Banner';
import About from '@/components/Home/About';
import Contact from '@/components/Home/Contact';
import TeamMember from '@/components/Home/TeamMember';
import Pricing from '@/components/Home/Pricing';
import WhatWeDo from '@/components/Home/WhatWeDo';
import Gallery from '@/components/Home/Gallery';
const Video = dynamic(() => import('@/components/Home/Video'), { ssr: false })
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [menu, setMenu] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <About />
      <TeamMember />
      <WhatWeDo />
      <Pricing />
      <Gallery />
      <Video />
      <Contact />
    </>
  )
}
